export const restaurants = [
    { name: "KFC", cuisine: "fastfood" , address:" Lot HS (D) 12038, PT 11378 Mukim, 32610 Bota, Perak"},
    { name: "Pizza Hut", cuisine: "fastfood" , address:"Ground Floor, No. 26, Persiaran SIBC 2, Bandar Seri Iskandar, 31750 Seri Iskandar, Perak"},
    { name: "McDonald's", cuisine: "fastfood" , address:" Plot 531, Bandar Seri Iskandar, Mukim, 32600, Perak"},
    { name: "A&W Seri Iskandar", cuisine: "fastfood" , address:" Plot 531, Bandar Seri Iskandar, Mukim, 32600, Perak"},
    { name: "SUBWAY SERI ISKANDAR", cuisine: "fastfood" , address:"26, Jalan PP 1, Bandar Universiti, 31750 Seri Iskander, Tronoh, Perak"},
    { name: "Ryan Nasi Kukus", cuisine: "local" , address:"Lot 148, Persiaran Dataran 2, Bandar Seri Iskandar, 32610 Seri Iskandar, Perak"},
    { name: "Ayam Penyet Medan Mba Rina", cuisine: "local" , address:"18, Persiaran Dataran 2, Bandar Seri Iskandar, 32600 Bota, Perak"},
    { name: "Syukor Burger Seri Iskandar", cuisine: "western" , address:"154, Lebuh SIBC, Bandar Seri Iskandar, 32600 Bota, 32610 Seri Iskandar, Perak"},
    { name: "Domino's Seri Iskandar", cuisine: "western" , address:"No. 1 & 1A, Jalan PP1, Bandar Universiti Seri Iskandar, 32610, Bandar Seri Iskan, 32610 Perak"},
    { name: "Starbucks", cuisine: "cafe" , address:" Petronas Station, Lot PTD 307&308, Jalan PP 1, Bandar Universiti, Mukim, 32610 Seri Iskandar, Perak"},
    { name: "The Black Caravan(Seri Iskandar)", cuisine: "western" , address:"No 36, Jalan PP5, Bandar Universiti, 31750 Seri Iskandar, Perak"},
    { name: "Little Ipoh", cuisine: "western" , address:"21, Jalan PP 1, Bandar Universiti Lakeville, 32610 Seri Iskandar, Perak"},
    { name: "Restaurant Al Bayan", cuisine: "mamak" , address:"Taman Maju, 32600 Seri Iskandar, Perak"},
    { name: "E One Roti Doll", cuisine: "local" , address:"Jalan PP5, 31750 Seri Iskandar, Perak"},
    { name: "Gomore Kitchen", cuisine: "local" , address:"No 28, Susur Bandar U1, Bandar Universiti, 32610 Seri Iskandar, Perak"},
    { name: "Restaurant T.A.P.A.U", cuisine: "local" , address:"8, Jalan PP 4, 31750 Seri Iskandar, Perak"},
    { name: "Farhan Tomyam Restaurant", cuisine: "local" , address:"31750 Seri Iskandar, Perak"},
    { name: "Restaurant Nasi Vanggey", cuisine: "mamak" , address:"Jln PP 6, 31750 Seri Iskandar, Perak"},
    { name: "Sizzling House Medan Selera Seri Iskandar", cuisine: "local" , address:"Medan Selera, 32610 Seri Iskandar, Perak"},
    { name: "The Syrian Kitchen", cuisine: "arab" , address:"11, Jalan Bandar U 1, 31750 Seri Iskandar, Perak"},
    { name: "Secret Recipe Seri Iskandar", cuisine: "cafe", address: "No. 2 & 2A, Jalan PP 2, Bandar Universiti Lakeville, 31750 Seri Iskandar, Perak"},
    { name: "Restoran Bamboo House Seri Iskandar", cuisine: "western",cuisine:"local" , address:"NO 143, Persiaran SIBC 9, Bandar Seri Iskandar, 32600 Bota, Perak"},
    { name: "Farhan cara & Restaurant", cuisine: "local" , address:" 3, Jalan PP 4, 31750 Seri Iskandar, Perak"},
    { name: "Cendol Leman SI Homemade", cuisine: "local" , address:"Dataran Niaga, 32610 Seri Iskandar, Perak"},
    { name: "Zuza Istiqomah Restoran & Catering", cuisine: "local" , address:"No 90, Persiaran Prima Seri Iskandar 3,Prima, 32610 Seri Iskandar, Perak"},
    { name: "Satay Grill Seri Iskandar", cuisine: "local" , address:"Kolej Vokasional Seri Iskandar, 32610 Seri Iskandar, Perak"},
    { name: "Jom Try Cafe", cuisine: "cafe" , address:" Persiaran Seri Iskandar Prima 4, 32600 Seri Iskandar, Perak"},
    { name: "Restoran Fariesha", cuisine: "local" , address:"31750 Seri Iskandar, Perak"},
    { name: "Sate Opah Viral Seri Iskandar", cuisine: "local" , address:"Jalan pp5, 32610 Seri Iskandar, Perak"},
    { name: "Z.R Restoran", cuisine: "local" , address:"Jln PP6, 31750 Seri Iskandar, Perak"},
    { name: "Restoran Selera Keluarga", cuisine: "local" , address:"12, Susur Bandar U 1, 31750 Seri Iskandar, Perak"},
    { name: "Kafe Laksa Ikan Sekoq Telur Sarang", cuisine: "local" , address:"31750 Seri Iskandar, Perak"},
    { name: "Warisan BUNDA", cuisine: "local" , address:"Gerai No 3 , Medan Selera, 31750 Seri Iskandar, Perak"},
    { name: "Cafe Nyah Basri", cuisine: "Cafe" , address:"46, Susur Bandar U 1, 31750 Seri Iskandar, Perak"},
    { name: "SUKA", cuisine: "local", cuisine:"western" , address:"NO .49, JALAN PP7, BANDAR U, 32610 Seri Iskandar, Perak"},
    { name: "IHSANI CAFE", cuisine: "cafe" , address:"55, Jln PP 5, Bandar Univerisiti, 32610 Seri Iskandar, Perak"},
    { name: "D Selera Biru", cuisine: "local" , address:"21, Jalan PP 3, 31750 Seri Iskandar, Perak"},
    { name: "NUR IMAN TOMYAM SEAFOOD", cuisine: "local" , address:"26, Jalan PP 3, BANDAR UNIVERSITI, 32610 Seri Iskandar, Perak"},
    { name: "Hafis Tomyam", cuisine: "local" , address:"19, Jln PP6, 31750 Seri Iskandar, Perak"},
    { name: "Restoran Sinar Madina", cuisine: "local" , address:"3, Jalan PP 4, 31750 Seri Iskandar, Perak"},
    { name: "Krismee TOMYAM Cafe", cuisine: "local" , address:"No.21 jln pp3, pusat bandar universiti, 32610 Seri Iskandar, Perak"},
    { name: "Citarasa Fartisha Restoran & Katering", cuisine: "local" , address:"Jalan PP 4, 31750 Seri Iskandar, Perak"},
    { name: "Stalista Street's Cafe", cuisine: "cafe",cuisine:"western" , address:"No 254, Lebuh SIBC, Bandar Seri Iskandar, 32610 Bota, Perak"},
    { name: "Restoran D'simpang", cuisine: "local" , address:"70, Persiaran SIBC 4, Bandar Seri Iskandar, 32600 Bota, Perak"},
    { name: "Kedai Nasi Balut", cuisine: "local" , address:"No 44, jalan susur bandar universiti 1 Bandar seri iskandar, 31750 Tronoh, Perak"},
    { name: "IKHWAN CAFE,seri iskandar", cuisine: "cafe" , address:"499, Persiaran SIBC 20, 32610 Seri Iskandar, Perak"},
    { name: "Warung nasi kukus Ayam Berempah", cuisine: "local" , address:"66, Susur Bandar U 3, 31750 Seri Iskandar, Perak"},
    { name: "YTR", cuisine: "local" , address:"2-34, Susur Bandar U 1, 31750 Seri Iskandar, Perak"},
    { name: "Nojom Hadramout Restaurant", cuisine: "western", cuisine:"arab" , address:"163, ground floor, 6, Lebuh SIBC, Bandar Seri Iskandar, 32610 Bota, Perak"},
    { name: "Pantai Timur Tomyam", cuisine: "local" , address:"Jalan PP 3, 31750 Seri Iskandar, Perak"},
    { name: "Nourish Cafe", cuisine: "cafe" , address:"139, Persiaran SIBC 4, Bandar Seri Iskandar, 32600 Bota, Perak"},
    { name: "Jom Lepak Station", cuisine: "cafe" , address:"No 49, Persiaran SIBC 4, Bandar Seri Iskandar, 32610 Seri Iskandar, Perak"},
    { name: "RF Cafe Restaurant", cuisine: "local" , address:"Bandar Seri Iskandar, 32600 Bota, Perak"},
    { name: "DAPOQ RIZTA", cuisine: "cafe" , address:"70, Jalan Tasik Indah 47, Bandar Universiti, 32610 Seri Iskandar, Perak"},
    { name: "Restoran Bunda Seri Iskandar", cuisine: "local" , address:"368, Persiaran SIBC 14, 32610 Seri Iskandar, Perak"},
    { name: "Restoran Darwisy Poktek", cuisine: "local" , address:"Persiaran SIBC 1, Bandar Seri Iskandar, 32600 Seri Iskandar, Perak"},
    { name: "Kopi Mesin Seri Iskandar", cuisine: "cafe" , address:"46, Persiaran Iskandar Perdana 19, Taman Seri Iskandar, 32610 Seri Iskandar, Perak"},
    { name: "MASTERGRILL SIBC Restaurant & Catering", cuisine: "western" , address:"380/381, 14, Lebuh SIBC, 32610 Seri Iskandar, Perak"},
    { name: "QZ Cafe", cuisine: "local", cuisine: "western" , address:" 23, Persiaran Iskandar Perdana 21, Taman Seri Iskandar, 32600 Seri Iskandar, Perak"},
    { name: "Rizqulllah", cuisine: "local", address:"Persiaran SIBC 1, Bandar Seri Iskandar, 32600 Bota, Perak"},
    { name: "Che'gu Cafe, Restaurant & Catering", cuisine: "western", address:"411 & 410 Persiaran SIBC 16 Seri Iskandar, 32600 Bota, Perak"},
    { name: "Restoran Tomyam Sri Maju", cuisine: "local", address:"Persiaran SIBC 11, Bandar Seri Iskandar, 32600 Bota, Perak"},
    { name: "Botaleft restaurant", cuisine: "local", address:"256,jalan bisnes center, Persiaran SIBC 9, 32600 Bota, Perak"},
    { name: "Richiamo Coffee Seri Iskandar", cuisine: "cafe", address:"No 2, Jalan PP7, Bandar Universiti, 32610 Seri Iskandar, Perak"},
    { name: "Lock Luck Char Kuey Teow", cuisine: "local", address:"Jln PP6, Bandar Universiti Lakeville, 32610 Seri Iskandar, Perak"}
 
    ];